Minor Changes
mental32/spotify.py pull request #14
Opened 2019-09-22 10:57 UTC by iterlace

- Missing Bearer Token exception added
- Typos fixed
- Search: `include_external` support added
- Another minor fixes

2019-09-22 21:26 UTC, mental32 requested changes
Thank you for taking an interest in spotify.py

I have reviewed your merge and have requested that some changes be made in the comments.
Additionally there is a superfluous file created `spotify_tests_/__init__.py` this will need to be removed.

2019-09-22 21:26 UTC, mental32 commented on spotify/client.py
> +        self.loop.run_until_complete(self.close())
This can fail if the event loop is already running or closed.
Also i'm not convinced that a `__del__` is really necessary.

2019-09-22 21:26 UTC, mental32 commented on spotify/http.py
> +        if not self._session.closed:
This is unneeded, `aiohttp.ClientSession.close` performs this check implicitly

2019-09-22 21:26 UTC, mental32 commented on spotify/http.py
> +        client_id: Optional[str],
The type annotation should just be `str`

2019-09-22 21:26 UTC, mental32 commented on spotify/http.py
> +        if include_external:
Best practice dictates explicitly using `is not None` to check NoneTypes

2019-09-22 21:26 UTC, mental32 commented on spotify/errors.py
> +class BearerTokenError(SpotifyException):
This should derive from `HTTPException`

2019-09-23 11:41 UTC, iterlace commented on spotify/client.py
> +        self.loop.run_until_complete(self.close())
Ok
I think, closing a session in `__del__` will not be superfluous, won't it?

2019-09-23 11:59 UTC, mental32 commented on spotify/client.py
> +        self.loop.run_until_complete(self.close())
Relying on del to perform possibly expensive clean ups is not something I'm too keen on.

This type of tear down can be achieved more explicitly with the usage of the async context manager

2019-09-23 12:15 UTC, iterlace commented on spotify/client.py
> +        self.loop.run_until_complete(self.close())
Okay, you're right

2019-09-23 12:25 UTC, iterlace commented
Each issue from our conversation was fixed

2019-09-23 12:55 UTC, mental32 reviewed
These changes look good to me, have you tested them?

2019-09-23 13:07 UTC, iterlace commented
Yes, I tested everything except the practical use of `include_external`: I didnt have time to search externally hosted songs, but theoretically it must work.

2019-09-23 13:21 UTC, merged